-- Postgres twin of migrations/005_sessions.sql (converted with `libsql-pg convert-schema`, reviewed).

create table if not exists cli_sessions (
  id text PRIMARY KEY,
  user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name text,
  host text,
  version text,
  cwd text,
  engine text,
  status text NOT NULL DEFAULT 'live',
  created_at bigint NOT NULL,
  last_seen_at bigint NOT NULL,
  ended_at bigint
);

CREATE INDEX IF NOT EXISTS idx_cli_sessions_user ON cli_sessions(user_id, last_seen_at DESC);

create table if not exists session_output (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id text NOT NULL REFERENCES cli_sessions(id) ON DELETE CASCADE,
  seq bigint NOT NULL,
  chunk text NOT NULL,
  created_at bigint NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_session_output ON session_output(session_id, seq);

create table if not exists session_commands (
  id text PRIMARY KEY,
  session_id text NOT NULL REFERENCES cli_sessions(id) ON DELETE CASCADE,
  body text NOT NULL,
  status text NOT NULL DEFAULT 'queued',
  created_at bigint NOT NULL,
  claimed_at bigint,
  done_at bigint
);

CREATE INDEX IF NOT EXISTS idx_session_commands ON session_commands(session_id, status, created_at);
