-- Postgres twin of migrations/006_moshpit.sql (converted with `libsql-pg convert-schema`, reviewed).

create table if not exists moshpit_tlds (
  tld text PRIMARY KEY,
  user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  owner_email text,
  owner_key text,
  alias_of text,
  created_at bigint NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_moshpit_tlds_user ON moshpit_tlds(user_id);

CREATE INDEX IF NOT EXISTS idx_moshpit_tlds_alias ON moshpit_tlds(alias_of);

create table if not exists moshpit_tld_log (
  seq bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tld text NOT NULL,
  user_id text NOT NULL,
  action text NOT NULL,
  at bigint NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_moshpit_log_tld ON moshpit_tld_log(tld);

create table if not exists moshpit_alias_exempt (
  tld text NOT NULL,
  label text NOT NULL,
  user_id text NOT NULL,
  created_at bigint NOT NULL,
  PRIMARY KEY (tld, label)
);
