// Keeping the bridge running across reboots.
//
// `dns enable` sets up two halves with different lifetimes: a systemd-resolved
// drop-in, which is a file and survives a reboot on its own, and the bridge
// process, which does not. After a restart the routing still points at a port
// with nothing behind it and every Moshpit name stops resolving with no
// obvious cause. This is the missing half, and it is why Moshpit DNS has held
// on servers — which got a unit installed by hand — and quietly fallen over on
// desktops, which never did.
//
// The unit is *generated* rather than shipped as a file, because no static
// unit can be correct for this tool. moshcode installs under the invoking
// user's $HOME, and its wrapper execs whatever `node` is first on PATH — which
// on any mise, nvm or asdf box is another shim under $HOME. The unit that
// shipped in examples/templates said:
//
//     ExecStart=/usr/bin/env moshcode dns start --port 5354
//     DynamicUser=yes
//     ProtectHome=yes
//
// and could not start on an ordinary install three times over: `moshcode` is
// not on systemd's PATH, the `node` its wrapper needs is not on it either, and
// ProtectHome hides the install from the service even if both had been found.
// It starts only where moshcode and node are both installed system-wide, which
// is the server case — the one that was already working.
//
// So the unit is written from the running process instead. `process.execPath`
// is an interpreter demonstrably able to run this code, because it is running
// it, and the entry is the script this very command was invoked from. Nothing
// is guessed and nothing depends on PATH.
import { spawn } from "node:child_process";
import { mkdir, rm, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { dirname, join } from "node:path";

export const UNIT_NAME = "moshcode-dns.service";

/**
 * Where the unit goes, and which systemctl reaches it.
 *
 * The user scope is the default because it is the one that fits how moshcode
 * is installed: a per-user tool, run by the user who owns the install, with
 * $HOME and the mise shims reachable exactly as they are in a shell. It also
 * puts the pidfile where the unprivileged `dns status` looks — systemd sets
 * XDG_RUNTIME_DIR for user units, so `pidfilePath()` resolves to
 * /run/user/<uid>/moshpit-dns.pid for the daemon and for the person asking
 * after it. Under a system unit those are two different paths.
 */
export function servicePaths({ system = false, home = homedir() } = {}) {
  return system
    ? { path: join("/etc/systemd/system", UNIT_NAME), systemctl: ["systemctl"], scope: "system" }
    : { path: join(home, ".config/systemd/user", UNIT_NAME), systemctl: ["systemctl", "--user"], scope: "user" };
}

/**
 * The unit text, pinned to this install.
 *
 * `ProtectHome` is deliberately absent rather than set to a weaker value: the
 * whole program lives under $HOME, so there is no setting of it that both
 * protects anything and lets the service start. The hardening that survives is
 * the hardening that does not contradict where the code is.
 */
export function serviceUnit({
  system = false,
  execPath = process.execPath,
  entry,
  port,
  registryBase = null,
  upstreams = [],
  proxy = null,
  user = process.env.USER || process.env.LOGNAME,
} = {}) {
  if (!entry) throw new Error("serviceUnit needs the entry script to run");

  const args = [entry, "dns", "start", "--port", String(port)];
  if (registryBase) args.push("--registry", registryBase);
  // The reason this unit exists at all is that the bridge now starts at boot —
  // and at boot the resolved drop-in is already in place, so the only
  // nameserver discovery can find is this bridge. It refuses loopback, comes up
  // with nowhere to forward, and NXDOMAINs every clearnet name including the
  // registry. Recorded here, while a working resolver is still around to be
  // asked, rather than rediscovered at boot when it cannot be.
  if (upstreams.length) args.push("--upstream", upstreams.join(","));
  // Without this the supervised bridge answers every name with its origin, and
  // the origin serves a certificate no CA signed — so `https://` fails on a
  // machine where the pinned-TLS proxy is installed, trusted and running.
  // `dns enable` has always probed for the proxy and passed it through;
  // `dns service` did not, which made a service-managed bridge the one way to
  // run Moshpit where HTTPS could never work.
  if (proxy) args.push("--proxy", proxy);
  const exec = [execPath, ...args].map((part) => (/\s/.test(part) ? JSON.stringify(part) : part)).join(" ");

  const lines = [
    "# Generated by `moshcode dns service`. Regenerate it rather than editing:",
    "# the paths below are this install's, and a moshcode or node that moves",
    "# leaves a unit that fails at 203/EXEC with nothing else to say.",
    "[Unit]",
    "Description=Moshpit DNS bridge",
    "Documentation=https://github.com/moshcoder/moshcode",
    "After=network-online.target",
    "Wants=network-online.target",
    "",
    "[Service]",
    "Type=simple",
    `ExecStart=${exec}`,
    "Restart=always",
    "RestartSec=2",
    // 5354 is unprivileged, so nothing here needs root or a capability.
    "NoNewPrivileges=yes",
    "PrivateTmp=yes",
  ];

  if (system) {
    // A system unit has no user of its own, so it has to be told which install
    // to run — and it is the only scope where that question has a wrong answer.
    lines.push(`User=${user}`);
  }

  lines.push(
    "",
    "[Install]",
    system ? "WantedBy=multi-user.target" : "WantedBy=default.target",
    "",
  );
  return lines.join("\n");
}

function run(command, args) {
  return new Promise((resolve) => {
    const child = spawn(command, args, { stdio: ["ignore", "pipe", "pipe"] });
    let err = "";
    child.stderr.on("data", (d) => (err += d));
    child.on("error", (error) => resolve({ ok: false, error: error.message }));
    child.on("exit", (code) => resolve({ ok: code === 0, error: err.trim() }));
  });
}

/** Write the unit and start it. Returns the steps taken, in order, for printing. */
export async function installService(unit, { system = false, home = homedir(), exec = run } = {}) {
  const { path, systemctl, scope } = servicePaths({ system, home });
  const steps = [];
  try {
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, unit);
    steps.push({ step: `wrote ${path}`, ok: true });
  } catch (error) {
    return { ok: false, path, scope, steps: [{ step: `could not write ${path}: ${error.message}`, ok: false }] };
  }

  const [cmd, ...flags] = systemctl;
  for (const args of [[...flags, "daemon-reload"], [...flags, "enable", "--now", UNIT_NAME]]) {
    const result = await exec(cmd, args);
    steps.push({ step: `${cmd} ${args.join(" ")}`, ok: result.ok, error: result.error });
    if (!result.ok) return { ok: false, path, scope, steps };
  }
  return { ok: true, path, scope, steps };
}

/** Stop it and take the unit away. Missing is not a failure — removal is idempotent. */
export async function removeService({ system = false, home = homedir(), exec = run } = {}) {
  const { path, systemctl, scope } = servicePaths({ system, home });
  const [cmd, ...flags] = systemctl;
  const steps = [];
  for (const args of [[...flags, "disable", "--now", UNIT_NAME]]) {
    const result = await exec(cmd, args);
    steps.push({ step: `${cmd} ${args.join(" ")}`, ok: result.ok, error: result.error });
  }
  await rm(path, { force: true });
  steps.push({ step: `removed ${path}`, ok: true });
  const reload = await exec(cmd, [...flags, "daemon-reload"]);
  steps.push({ step: `${cmd} ${[...flags, "daemon-reload"].join(" ")}`, ok: reload.ok, error: reload.error });
  return { ok: true, path, scope, steps };
}
